CREATE TABLE category
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name       VARCHAR(255),
    definition VARCHAR(1000),
    low_val    DOUBLE PRECISION,
    high_val   DOUBLE PRECISION,
    CONSTRAINT pk_category PRIMARY KEY (id)
);

CREATE TABLE measurement
(
    id     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "user" VARCHAR(255)                            NOT NULL,
    date   date                                    NOT NULL,
    height DOUBLE PRECISION                        NOT NULL,
    weight DOUBLE PRECISION                        NOT NULL,
    CONSTRAINT pk_measurement PRIMARY KEY (id)
);

CREATE TABLE statistic
(
    iso_code   VARCHAR(255) NOT NULL,
    country    VARCHAR(255),
    rank_val   INTEGER,
    both_gender DOUBLE PRECISION,
    male       DOUBLE PRECISION,
    female     DOUBLE PRECISION,
    CONSTRAINT pk_statistic PRIMARY KEY (iso_code)
);

CREATE TABLE sub_category
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(255),
    low_val     DOUBLE PRECISION,
    high_val    DOUBLE PRECISION,
    category_id BIGINT,
    CONSTRAINT pk_sub_category PRIMARY KEY (id)
);

ALTER TABLE sub_category
    ADD CONSTRAINT FK_SUB_CATEGORY_ON_CATEGORY FOREIGN KEY (category_id) REFERENCES category (id);
