CREATE TABLE Principal
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    firstname VARCHAR(255)                            NOT NULL,
    lastname  VARCHAR(255)                            NOT NULL,
    username  VARCHAR(255)                            NOT NULL,
    password  VARCHAR(255)                             NOT NULL,
    CONSTRAINT pk_principal PRIMARY KEY (id),
    CONSTRAINT uc_principal_username UNIQUE (username)
);

ALTER TABLE Measurement
    ADD principal_id BIGINT;

ALTER TABLE Measurement
    ADD CONSTRAINT FK_MEASUREMENT_ON_PRINCIPAL FOREIGN KEY (principal_id) REFERENCES Principal (id);

ALTER TABLE measurement
    DROP COLUMN person;
